### ISSUE TITLE
執行 uclliu.exe 出現錯誤

### ISSUE THREAD

**Issue by ycl413** [shadowjohn/UCL_LIU#1]
Fatal Error:
Failed to execute script uclliu

liu-uni.tab 已存在
liu.cin 自動產生在同目錄下

**Comment by shadowjohn** [comment]
能用cmd的方式執行看看嗎，需要更多錯誤訊息

**Comment by ycl413** [comment]
在 cmd 的 Administrator 下執行，一樣錯誤訊息。
win10 64
![fatal error](https://user-images.githubusercontent.com/30377030/28505176-e261a23e-6fe6-11e7-87f0-038d89d3ca6a.png)

**Comment by shadowjohn** [comment]
我大概知道原因了
解決方法
1、先把整個dist目錄複製到別的地方，如D:\
2、確定工作管理員裡都沒有python、uclliu.exe 等程序
3、刪掉dist裡的cin，留 uclliu.exe、pinyi.txt、你的liu-uni.tab 
執行uclliu.exe ，首次執行大概需要1分鐘，他會把 tab->cin->json會花比較多時間
因為完全沒有提示，所以您就稍等一下
會發生fatal是因為重覆執行的關係，我不知道為啥重覆執行多次後，即時刪了cin還是會發生fatal
這個之後在修
把上述的檔案複製出去，再執行就會正常

#18、tab->cin->json有點久，所以預計再加一個字根檔轉換中的進度畫面
#23、增加啟動時版本提示，有助於確認目前版本，之後版號會開始增加
我會再一併更新

**Comment by shadowjohn** [comment]
補充，應該是發生在dist存放的路徑中有中文目錄才會造成轉json失敗
可能的bug應該是在 cintojson.py 裡面的目錄，在處理中文目錄有問題
這部分我會再調整修正 :)

**Comment by ycl413** [comment]
我在第二台電腦(Win10 x64, 從末曾執行過 uclliu)，照著上面方法，重新下載 dist，放到英文檔名資料夾。
執行程式後製造出 cin 以後還是出現同樣的錯誤。
![uclliu error](https://user-images.githubusercontent.com/30377030/28526402-10a7a1fa-704d-11e7-8aa3-91d2d5ddfd8e.JPG)

**Comment by shadowjohn** [comment]
您好，重抓新版UCLLIU.exe再試一次~應該已修正好了
再不行就神奇了

**Comment by ycl413** [comment]
真的還是不行

**Comment by shadowjohn** [comment]
能加個Line嗎，我看一下是什麼原因

**Comment by shadowjohn** [comment]
我剛才用一台空的 windows xp 測試
發現psutils如果要相容早期的作業系統，需降為 3.4.2 (我原本電腦是5.x)
不過我研究出pyinstaller，可以作出 uclliu_debug.exe
您可以抓uclliu_debug.exe  執行看看，如果這次有錯誤，我想應該可以印在console裡面了
參考看看
不確定會不會是psutils的問題，目前我在windows xp 、windows 10 64、windows 2008 server都測過可以用

**Comment by ycl413** [comment]
console 輸出：
-------------------------------------------------------------------------------------------------------------------

C:\Apps\dist>uclliu_debug.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\Apps\dist\uclliu_debug.exe
LOADER: homepath is C:\Apps\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Apps\dist\uclliu_debug.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is C:\Apps\dist\uclliu_debug.exe
LOADER: homepath is C:\Apps\dist
LOADER: _MEIPASS2 is C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842
LOADER: archivename is C:\Apps\dist\uclliu_debug.exe
LOADER: SetDllDirectory(C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842\uclliu_debug.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18~1
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename uclliu_debug.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_win32comgenpy.py
LOADER: Running uclliu.py
liu
liu.cin
Traceback (most recent call last):
  File "uclliu.pyw", line 96, in <module>
  File "cintojson.py", line 232, in run
  File "cintojson.py", line 327, in getCharSet
TypeError: ord() expected a character, but string of length 0 found
Failed to execute script uclliu
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: -1)
LOADER: Doing cleanup
LOADER: Freeing archive status for C:\Apps\dist\uclliu_debug.exe

**Comment by ycl413** [comment]
Console 輸出：
 ```
C:\Apps\dist>uclliu_debug.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\Apps\dist\uclliu_debug.exe
LOADER: homepath is C:\Apps\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Apps\dist\uclliu_debug.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is C:\Apps\dist\uclliu_debug.exe
LOADER: homepath is C:\Apps\dist
LOADER: _MEIPASS2 is C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842
LOADER: archivename is C:\Apps\dist\uclliu_debug.exe
LOADER: SetDllDirectory(C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842\uclliu_debug.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18~1
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename uclliu_debug.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\YUCHAN~1\AppData\Local\Temp\_MEI18842
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_win32comgenpy.py
LOADER: Running uclliu.py
liu
liu.cin
Traceback (most recent call last):
  File "uclliu.pyw", line 96, in <module>
  File "cintojson.py", line 232, in run
  File "cintojson.py", line 327, in getCharSet
TypeError: ord() expected a character, but string of length 0 found
Failed to execute script uclliu
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: -1)
LOADER: Doing cleanup
LOADER: Freeing archive status for C:\Apps\dist\uclliu_debug.exe

```

**Comment by shadowjohn** [comment]
能寄您的 liu-uni.tab、liu.cin給我看看嗎，linainverseshadow@gmail.com

**Comment by ycl413** [comment]
已寄

**Comment by shadowjohn** [comment]
我已確定你的 liu-uni.tab 有問題，換一個應該就可以了

**Comment by shadowjohn** [comment]
換掉liu-uni.tab，記得要把 liu.cin 刪掉再重跑

**Comment by ycl413** [comment]
我這是嘸蝦米 7.0 安裝後在 C:\Windows\SysWOW64 下找到的四個 liu-uni.tab
liu-uni.tab
liu-uni2.tab
liu-uni3.tab
liu-uni4.tab
2,3,4都可用，但字根不正確。1就是我寄給你的那個。
我再找找別版好了。謝謝

**Comment by shadowjohn** [comment]
您好，只有liu-uni.tab可以用，其他的我不清楚~~

我剛才試用嘸蝦米試用版裡的 liu-uni.tab
http://boshiamy.com/download_trial.php
嘸蝦米™輸入法（Boshiamy™）J 試用版
C:\Program Files\BoshiamyTIP  --> 安裝後，您也可以在此找到只有6000字的liu-uni.tab

這個版本的tab也是可以用的

**Comment by shadowjohn** [comment]
Hi ycl413,
您可以去嘸蝦米網站抓官方的 j 版試用版，裡面附的 liu-uni.tab 至少也有5、6000字可以用
我測過是可以的，不過有些字會缺，要好用還是要正版的字根檔才行

**Comment by JoeHsiao** [comment]
這個錯誤只會發生在有UCLLIU.ini的情況下
每次都要刪.ini檔很煩

Windows 10 x64

**Comment by shadowjohn** [comment]
@JoeHsiao 
請問您是用最新版的嗎? 請按 ,,,version 確認一下您是用哪個版本，最新是 1.21
然後錯誤的內容是什麼? 可以貼來看看嗎

**Comment by JoeHsiao** [comment]
版本是1.21
錯誤內容跟3樓貼的圖一模一樣

錯誤產生流程：
(桌面上有liu.json和uclliu.exe)
1. 執行uclliu.exe (桌面產生UCLLIU.ini)
2. 按「肥半」上的叉叉關掉輸入法
3. 再執行uclliu.exe
4. 錯誤對話框就跳出來了

如果在第3步之前移除UCLLIU.ini的話就不會有錯誤

有需要可以寄liu.json給你

**Comment by shadowjohn** [comment]
@JoeHsiao 


UCLLIU.ini 裡面是一些環境設定

[DEFAULT]
short_mode = 0   # 0 指的是否肥米使用短版模式，同 ,,,s ，1 同 ,,,l (L)
zoom = 1.00 # 肥米的UI的大小比例，如 ,,,- 縮小，,,,+ 放大
send_kind_2_big5 = # 被指定的 exe ，出字方式使用 big5 出字，有些公家機關的程式會需要這種…
send_kind_1_paste = # 被指定的 exe ，出字方式使用 複製貼上，如 pcman
alpha = 1 # 肥米的透明度， 0 ~ 1 數字越小越透明
y = 578 # 記憶肥米最後移到的位置 y
x = 416 # 記憶肥米最後移到的位置 x

理論上肥米在使用時，是不會持續鎖住 UCLLIU.ini 這個檔案，能否請您執行完肥米，產生的 UCLLIU.ini
檢查一下內容是否如上，我在想是不是有可能 ini 檔案入失敗，所以肥米無法正常讀出內容~
那我就要再加個 try cache 避免類似的情況發生

我自己試了一下我的環境是還滿正常的，如附件

[2019-07-22_08_39_40.zip](https://github.com/shadowjohn/UCL_LIU/files/3415257/2019-07-22_08_39_40.zip)

**Comment by JoeHsiao** [comment]
我同意
1. uclliu.pyw讀寫UCLLIU.ini的部分看起來沒問題
2. 我手打了一份簡易liu.json，裡面只有一個字，還是會出錯。應該不是換行符號的問題

我用的是windows 10英文版，沒有裝中文語系，會和這個有關嗎？

**Comment by shadowjohn** [comment]
liu.json 有存成無bom的 utf-8 格式嗎?

JoeHsiao <notifications@github.com> 於 2019年7月22日 週一 上午10:20寫道：

**Comment by shadowjohn** [comment]
無中文語系可能也有影響，但我不確定
我再找時間試看看

**Comment by JoeHsiao** [comment]
很有可能是編碼的問題

liu.json本來是utf-8，沒問題
我把它改成utf-8 with BOM之後(用notepad -> save as)，就算沒有UCLLIU.ini，也會產生一樣的錯誤
其他編碼也一樣會錯，只有utf-8才可以

回過頭來講，查了UCLLIU.ini是utf-8沒錯
讓我懷疑難道程式裡的那些key ('X','Y','ALPHA','ZOOM','SHORT_MODE','SEND_KIND_1_PASTE','SEND_KIND_2_BIG5') 是非utf-8，所以才會對不起來？

**Comment by shadowjohn** [comment]
你得用notepad++ 或 pspad 的程式來確認，而且儲存時，「不可以有bom」
存成bom等同在檔案開頭加上  0xef,0xbb,0xbf
你用一般微軟notepad是看不到的
這會造成解json失敗
不然我要再調整一下開 liu.json 的程式碼，開啟時如果檔頭有bom自動刪除再進行 json decode

JoeHsiao <notifications@github.com> 於 2019年7月22日 週一 下午12:51寫道：

**Comment by JoeHsiao** [comment]
別誤會，liu.json沒有問題
只是我故意手動把liu.json改成非utf8的encoding，會造成一模一樣的錯誤
我只是由此來推斷有可能UCLLIU.ini的encoding是非utf8

**Comment by shadowjohn** [comment]
UCLLIU.ini 裡面沒有任何中文字，是不是utf-8應該不重要，重要的還是頭三個字 bom...

JoeHsiao <notifications@github.com> 於 2019年7月24日 週三 上午10:51寫道：

**Comment by JoeHsiao** [comment]
用hexviewer看過，UCLLIU.ini前3個BYTE不是0xef,0xbb,0xbf
我直接給你我的[UCLLIU.ini](https://srv-file1.gofile.io/download/wxPi35/UCLLIU.ini)好了，看你會不會出錯

**Comment by shadowjohn** [comment]
好的，麻煩您

JoeHsiao <notifications@github.com> 於 2019年7月25日 週四 08:39 寫道：

**Comment by shadowjohn** [comment]
您分享的這個檔案，我無法下載
You are not authorized to download this file.

寄到我的 email 吧 : linainverseshadow@gmail.com
