### ISSUE TITLE
1.33 版的簡根提示消失了。

### ISSUE THREAD

**Issue by YukieChen** [shadowjohn/UCL_LIU#11]
剛剛注意到 1.33 版的一個 Bug：顯示短根的功能消失了。

比方說打 lonu 這個碼輸出『膏』時，在勾選『顯示短根』選項時應該會提示：『簡根：QUE』，可是換 1.33 版之後，這個簡根提示消失了。

我重新下載了 1.32 版，這個功能就又正常，所以可以確定是 1.33 版的 Bug 嘍。

**Comment by shadowjohn** [comment]
感謝通知，這二天有空我調整一下~

**Comment by shadowjohn** [comment]
YukieChen 您好，
1.34 已修正~
修正以下工項

(2021-07-22) V1.34 版：
病毒碼提交掃描：1.34 https://www.microsoft.com/en-us/wdsi/submission/61c84515-3890-4e51-be52-ab24e8024c93
1. 117、當點右下角「肥」叫出選單，應該把「肥」切換成「英」，以免檔到畫面。
2. 118、顯示短根，因為分頁的關係故障，如果不是透過選字，不會出現短根，例如：肥 ucl 空白，跟 ucl 0，按 ucl 0 才出現短根
3. 119、send_kind_1_paste、send_kind_2_big5 ... 出字方式的執行檔名，要 trim，避免使用者多打了空白、過濾重複值
4. 120、當點右下角「肥」叫出選單，應該把「全」切換成「半」，以免檔到畫面。


目前等待送審中
![image](https://user-images.githubusercontent.com/1788472/126589222-626f8186-34d0-40ca-814e-e7fb5fd33498.png)

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/126607738-77dfda6c-54e3-4410-902d-cc52e675e2bc.png)
掃描結果已完成^_^~

**Comment by YukieChen** [comment]
謝謝您這麼快就更新版本。

剛剛試用了一下，發現祇要 send_kind_1_paste = 這一行加上參數，就無法執行肥米。

不論是
send_kind_1_paste = PhotoFiltre7.exe,pproconf.exe
send_kind_1_paste = PhotoFiltre7.exe, pproconf.exe
send_kind_1_paste = PhotoFiltre7.exe, pproconf.exe,

都無法執行。甚至光是加入
send_kind_1_paste = PhotoFiltre7.exe

也無法執行，會出現『Failed to execute script ucliu』的錯誤訊息。

不過右下角程式設定頁現在不會被其他視窗擋住了，很棒。

**Comment by shadowjohn** [comment]
哦哦~ 試了一下確實有這問題
更新一下 1.35
修正 array_remove_empty_and_trim 應該可以正常了~

**Comment by YukieChen** [comment]
謝謝您！！

剛剛試用了 1.36 版，功能正常了，謝謝您總是很快的修正，使用者太有福氣了。 :D

**Comment by shadowjohn** [comment]
申請結案，另外 1.37 版也上嘍~
