### ISSUE TITLE
打不出難字，如堃...

### ISSUE THREAD

**Issue by wei10cool** [shadowjohn/UCL_LIU#14]
使用liu-uni.tab 136kb版本打不出難字

**Comment by shadowjohn** [comment]
當然…您那個大概是早期試用版附的 tab 檔吧
去抓其他較完整的吧^^"
要重轉的話，請把 liu.json 、liu.cin 刪掉，重新放 tab 再重新執行肥米
肥米支援的來源很多，詳見 readme.md

**Comment by shadowjohn** [comment]
把 liu.json 、liu.cin、tab 都刪掉
可以抓 https://raw.githubusercontent.com/ianzhuo/irime-liur/master/liur_Trad.dict.yaml
跟肥米主程式放一塊
再執行 uclliu.exe 即可
這個字庫也是滿好打的

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/135558540-c742df99-213f-43a4-b85a-223eb2b9e342.png)
