### ISSUE TITLE
不使用時，可以完全隱藏嗎？

### ISSUE THREAD

**Issue by devenhala** [shadowjohn/UCL_LIU#15]
謝謝你的開發，這非常類似以前使用的習慣，符合我的需求。
請問不使用時，可以完全隱藏嗎？目前只是半透明在背景。

![image](https://user-images.githubusercontent.com/23516205/142748364-805aeb55-6056-4b79-8e42-3229e035eb5c.png)

**Comment by shadowjohn** [comment]
謝謝您的回饋~
下一版(1.39版) 作給您
剛才複習原始碼
大概在 #1192 行，英/半 時的 set_opacity 改成 0 就會完全隱形了
到時我再註冊一個變數到 uclliu.ini 吧
原則上會取 non_ucl_alpha = 0.2
到時您手動改成 0 即可

或是作在選單裡，
肥模式的透明度 0% ~ 100% 
英模式的透明度 0% ~ 100%

![image](https://user-images.githubusercontent.com/1788472/142749822-b984e4ca-8a59-4657-aace-46c058f4e0de.png)

**Comment by devenhala** [comment]
大感謝，期待你的更新。

另外小小的介面問題，那位字體似乎大過於介面，
這是 win10 的字體關係嗎？能否優化呢？

**Comment by shadowjohn** [comment]
可能每個人使用螢幕解析度不同的關係吧，我是根據我自己常用的解析度，配合接近老人老花使用的程度
總之大家終有一天也會老花，先這樣就好 XD

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/144352571-f4bfbf1b-3357-402d-95f5-e5859d4c5aa5.png)
1.39 努力開發中~

**Comment by devenhala** [comment]
太棒了，期待，有沒機會也開發 android 平台的呢？

**Comment by shadowjohn** [comment]
1.39 beta release
android 我是用萊姆輸入掛載嘸蝦米字根，用起來很順，也有語音輸入
所以應該不會開發了

**Comment by devenhala** [comment]
剛才下載使用正常，非常好用，感謝。

**Comment by shadowjohn** [comment]
謝謝您的支持，祝您使用愉快
有任何想法意見都歡迎回饋^_^~
