### ISSUE TITLE
注音模式下，一聲無法選字

### ISSUE THREAD

**Issue by devenhala** [shadowjohn/UCL_LIU#17]
Hi,

請問，在 '; 的注意模式下，如果是一聲的注意，似乎無法選到字。

**Comment by shadowjohn** [comment]
Hi Devenhala,
謝謝您的回報~

嗯…目前注音的選字是利用 SPACE、 VRSWL ( 0 1 2 3 4 5 6...)
如 飛 ';zo 
就得輸入  ;lzov space
選字時的換頁是 shift+space
下一版我再改成注音模式時的數字可以出字~
![image](https://user-images.githubusercontent.com/1788472/152985709-21e4881a-25b8-45ed-a700-f2bd57abdb5d.png)

**Comment by devenhala** [comment]
另外請教有關同音字的打法，我打 'pns 沒辦法出現同音字，
我有放 pinyi.txt 字庫在裡面，為何不會出現呢？



![image](https://user-images.githubusercontent.com/23516205/153143827-7b9fb153-f065-499a-8060-5fc43108dc95.png)

![image](https://user-images.githubusercontent.com/23516205/153143943-4270b5c9-8a04-4d6b-89bb-f5f811f8a2f0.png)

**Comment by shadowjohn** [comment]
'pns 後要打空白鍵

![image](https://user-images.githubusercontent.com/1788472/153156113-1d5b1f50-097c-4134-876d-9bc9e9cf203a.png)

**Comment by devenhala** [comment]
那這樣我了解，我再調整使用習慣，謝謝。

**Comment by devenhala** [comment]
謝謝你的更新

**Comment by shadowjohn** [comment]
> 謝謝你的更新
感謝不離不棄支持肥米輸入法 XD

**Comment by shadowjohn** [comment]
@devenhala 
Hi~ [devenhala](https://github.com/devenhala)
我有更新 1.51 版注音操作的方式
這次在發聲送出後，以數字鍵選字，如果有下頁可以用 shift + space 換頁
操作注音時也有加入礎楚防呆，可以更新試試^^

**Comment by devenhala** [comment]
不好意思，這幾天剛好在忙，沒有即時回覆，我目前測試可以正常使用，太感謝你了。

**Comment by shadowjohn** [comment]
Hi @devenhala ,
謝謝您的支持~~
這個功能趨於完整也是個成就~
注音還有些更進階嚴格的輸入限制，有想到再加
有任何使用問題也都歡迎再開 issue ，繼續努力
