### ISSUE TITLE
請問能自訂簡繁轉換字嗎？

### ISSUE THREAD

**Issue by jason20211010** [shadowjohn/UCL_LIU#18]
最近使用打繁出簡發現有時打出來的還是繁體字，例如打「嘆」並不能轉成「叹」，請教有什麼方法可以自訂這些單字？

**Comment by shadowjohn** [comment]
https://github.com/shadowjohn/UCL_LIU/blob/master/stts.py

嘆 換不成 叹~
真的耶~没想到這個簡繁對照表沒有這麼完美...
簡繁對照沒有自定擴充~

晚點我再找一下有沒有更完整的對照表重新發一版

**Comment by shadowjohn** [comment]
剛才已作好 1.40 版修正這個問題，我先測試一下~
stts.py 裡原先使用台灣碼農的繁簡對照表，發現有缺漏字(2553字)，改使用：hanziconv (2704字)
https://github.com/berniey/hanziconv/blob/master/hanziconv/charmap.py

晚點 ok 的話，我就合併到主線

测试中~~~
嘆息->叹息
按赞->观注->三连->大铃当

最近使用打繁出简发现有时打出来的还是繁体字，例如打「叹」并不能转成「叹」，请教有什么方法可以自订这些单字？

**Comment by shadowjohn** [comment]
申請結案

**Comment by shadowjohn** [comment]
1.41 版會修正少一個「拚/拼」
