### ISSUE TITLE
英數狀態會自己切回肥半

### ISSUE THREAD

**Issue by jetliao0909** [shadowjohn/UCL_LIU#2]
沒有按shift的情形，切換不同的應用程式時會不定時回復成肥半

**Comment by shadowjohn** [comment]
會改變 英/肥的情況，只有以下的狀況:
語法:toggle_ucl
757行，用途：按到肥米列的「肥 或 英」
1186行，用途：,,,c  「簡」 繁 切換時，會幫忙換成 肥
1200行，用途：,,,t  簡 「繁」 切換時，會幫忙換成 肥
1367行，用途：最像bug描述的部分，當按著shift時，再按右邊的數字鍵，結果 肥/英一直變
我已忘了當初這段在修正什麼，好像是打game時想排除的bug，但弄巧成拙
1537行，用途：鍵盤放開按鍵時，當按鍵是左shift或右shift，且沒有其他組合鍵，正常的切換 英/肥

您在切換不同應用程式時，是用 alt+tab 嗎，如果是的話，應該是不會觸發，英/肥 切換

**Comment by shadowjohn** [comment]
我想起來了，1367這段，應該是指右邊方向鍵
不管 numlock 開或關，shift+右邊數字鍵，要「上下左右」
這邊確實有bug存在

**Comment by shadowjohn** [comment]
也有可能並不是真的是「英」模式，而是被隱藏的「肥」
當肥模式沒有任何輸入時，切換視窗是會把「肥」的介面蓋住，當有任何輸入，又會再浮上來，包含F5
唯有在「肥」模式，會強制在有任何打字時浮起
如果要完全避免這個狀況，也許要區分一下哪些按鍵才需要浮起，哪些不用

**Comment by shadowjohn** [comment]
1.15 版有調整UI上浮的問題，可再試試

**Comment by jetliao0909** [comment]
1.15看起來已修正，的確是UI潛在背景。
胖半，能夠即時上浮會更好，切換APP時似乎有個秒等級的delay
而特別在CHROME裡，即便在同一tab，只要點了滑鼠就會立即潛水，delay一下又浮出

**Comment by shadowjohn** [comment]
是的，根據程式碼 1772行 至1775行，每0.01秒會刷新 UI 來確保 肥 模式可以置頂
如果把這個值再改快，會造成肥米太吃太多CPU去維持置頂的 UI 刷新。
也許要研究看看有沒有 window 視窗切換的事件能不能去偵測與trigger，這樣肥米就可以改成被動更新 UI。
有閒再作 :)
