### ISSUE TITLE
英文版win11 工具欄無法顯示

### ISSUE THREAD

**Issue by Chuanhuan** [shadowjohn/UCL_LIU#28]
![image](https://user-images.githubusercontent.com/30125119/203312349-10d751e1-684b-4139-81b0-a2e516334256.png)

這是我的情況，我的版本是1.47
先謝謝大大無私的分享

**Comment by shadowjohn** [comment]
謝謝 @Chuanhuan 
英文版win11啊~~
晚點我試看看選單的部分要指定哪一種字型才能正常出字
其他功能正常嗎 :O ?

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/203499990-5f6b32ed-ae6f-49ef-8845-b4c482712ff9.png)
先給您對照著用^^"

**Comment by Chuanhuan** [comment]
@shadowjohn 是的，其他輸入都沒有問題，是big5及Unicode 問題嗎？

**Comment by shadowjohn** [comment]
我覺得不像big5跟unicode的問題
應該是右下角選單的中文，win11 預設的字型可能沒有包含中文字
traybar.py 裡面目前沒有指定任何字型檔
我研究看看怎麼指定，您能幫忙看看 c:\windows\fonts\ 裡有沒有 Msjh.ttc 這個檔案，微軟正黑體
有的話我預設改這個

**Comment by shadowjohn** [comment]
亦可能是 win32_adapter.py 裡 encode_for_locale

**Comment by shadowjohn** [comment]
locale.getpreferredencoding
https://docs.python.org/zh-tw/3/library/locale.html
晚上我找台vm試試看~

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/203551861-0b828dc6-e310-474d-afb0-abc88fb374b4.png)
環境作出來了，嘗試解決中

**Comment by shadowjohn** [comment]
@Chuanhuan 
您好，目前找到一個解法：
總之就是把選單的文字全定義成 unicode，然後系統要勾這個 Beta 的選單後重開機
其實就是強制指定系統都用 chcp 65001 運行，然後版本還得在 win11 編輯才能正常
![image](https://user-images.githubusercontent.com/1788472/203585699-ef3d58db-eb34-412f-acbc-f14b7e73b600.png)
但這個作法感覺不太好，有點太複雜了，且要使用者自己勾選

非中文版作業系統(非chcp cp950)目前應該只有右下選單有問題，我之後再作一個i18n.py 裡面將選單的中文對照轉英文
不然就要再研究看看怎麼解^^"

![image](https://user-images.githubusercontent.com/1788472/203607723-46baf64b-0c27-4eb8-b53b-fb31c27e7404.png)

**Comment by Chuanhuan** [comment]
@shadowjohn 
太感謝您對這問題的重視！
我其實也很少使用windows，我使用android tab s8+ run proot archlinux..
不過，我會試試看，真的很感謝！！

**Comment by Chuanhuan** [comment]
@shadowjohn 
![image](https://user-images.githubusercontent.com/30125119/203739287-d18af7c1-35ea-462e-80ee-189b38f38ce8.png)

![Screenshot 2022-11-24 165530](https://user-images.githubusercontent.com/30125119/203738605-a20c0354-c916-4432-8de6-04771d358115.png)
我follow你的方式，會出現failed to execute的error，可能是我win11 22H2 OS Build: 22621.898 系統上的問題嗎？

**Comment by shadowjohn** [comment]
失敗是正常的，因為你用的不是 win11 重編的結果，且要 1.49版
還是先不要這樣用~我晚點作好 i18n 多國語系版再提供下載連結給您

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/205230801-60d44190-38c6-4ad2-bb8e-c60841171a79.png)
Hi, @Chuanhuan 
好久不見，我試了許多方法還是沒能在不改系統環境設定的情況成功
先用英文介面頂著先~~
請更新至 1.49 
之前那個勾  UTF-8 的部分就不要勾了~~
https://raw.githubusercontent.com/shadowjohn/UCL_LIU/master/dist/uclliu.exe

**Comment by Chuanhuan** [comment]
@shadowjohn 
感謝！！！這樣是正常使用了！
你的英文翻的已經很好！我會使用看看有什麼問題，再給你feedback，

之前有時注音在選定，數字鍵1、2，好像會加在聲母上，
本來想確切找出特定字，但幾日出差也沒特別去指出問題…
若1.49版還有持續注音選字問題，我會再開新issues

不過很感謝現在英文功能呈現問題，得到暫時解決方案……

**Comment by shadowjohn** [comment]
嗯嗯，注音現在選字偷懶仍用 VRSF在選…

**Comment by shadowjohn** [comment]
這筆申請結案

**Comment by shadowjohn** [comment]
@Chuanhuan 您好,
注音在最新版也改好了~

**Comment by Chuanhuan** [comment]
> @Chuanhuan 您好, 注音在最新版也改好了~

You're the man!! Will try.
