### ISSUE TITLE
出字異常

### ISSUE THREAD

**Issue by Benson9954029** [shadowjohn/UCL_LIU#30]
軟體Neovim(nvim-qt)
版本NVIM v0.8.1
下載位置 https://github.com/neovim/neovim/releases
環境win11
肥蝦米版本:UCL 1.49
在上面打停字時會出"\"
有試過貼上模式 但在neovim中要用"*p 所以會失敗
目前打了很多字只有這個字有問題 
試過https://github.com/fcitx/fcitx-table-extra/blob/master/tables/boshiamy.txt
也是一樣，如果您有頭緒可以試著處理 沒有就放著吧 目前除了這個字以外都正常
![neovim_gif](https://user-images.githubusercontent.com/28132352/206653380-61a2e4a4-6be9-4b70-9ba5-61d1502f4408.gif)

**Comment by shadowjohn** [comment]
沒用過 Neovim 
晚上我用 win11 sandbox 試試，也許可以加個例外
pietty、putty 也是得加例外才能正常使用

**Comment by shadowjohn** [comment]
https://user-images.githubusercontent.com/1788472/206668264-4898a1cf-95b4-430e-979e-3e25c5420d06.mp4

如果改用 paste 上字，是有機會可以修正，不過我再想看看為什麼只有停 這個字在正常模式有問題 :(
paste 上字得透過剪貼簿，很不優雅~~

**Comment by shadowjohn** [comment]
@Benson9954029 
我加了例外判斷，在正常出字時，判斷執行程序是 neovim-qt，且出字裡包含「停」，改用貼上出字

https://github.com/shadowjohn/UCL_LIU/blob/Feature_V1.50/dist/uclliu.exe
先用這個方式排除吧~感覺是neovim 裡可能對塞unicode 有狀況
不過不知道會不會有其他字也會有一樣的狀況，我把 停 四週的字碼都試了一輪，不過沒發現

**Comment by Benson9954029** [comment]
哦哦 假日比較忙沒空回應您，
試了一下V1.50的出字是ok的  
感謝您的迅速回應
