### ISSUE TITLE
請問 vscode 底下無法叫出輸入法的原因會是什麼呢？

### ISSUE THREAD

**Issue by frankc7777777** [shadowjohn/UCL_LIU#33]
先感謝大大提供的好用工具，小弟真的受益良多！！

只是小弟想要在 vscode 底下打開輸入法視窗，但都叫不出來，
會是因為熱鍵被 vscode 攔截走了嗎？
請問是否有辦法解決呢？

再次感謝大大無私的分享！！

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/210356008-37f1d3de-dfa4-4426-b86d-f422dc552e21.png)
我試是滿正常的，不過我是有在肥米的選單勾「使用 CTRL+SPACE」切換輸入法
![image](https://user-images.githubusercontent.com/1788472/210356087-5f3fa6fc-912a-4c3c-a3d4-340a052b1a7d.png)

如果還是不行的話，開肥米用系統管理員開看看
![image](https://user-images.githubusercontent.com/1788472/210356238-046e2ae4-454c-4dd2-8b3c-6a4d2ca489dd.png)

大多數無法正常切換輸入法的狀況，可能是啟動肥米時是一般使用者，但你跑的程式是系統管理員
提到同一個等級應該就正常了

**Comment by frankc7777777** [comment]
感謝大大的提醒與解釋！！ 小弟剛剛試了一下，沒想到真的是系統權限的問題！ 我忘了我的 vscode 是開系統管理員權限，但肥米輸入法就沒注意到也要一起開系統管理員權限說！ 真的是太感謝了！！  ^^

**Comment by shadowjohn** [comment]
@frankc7777777 
謝謝您的支持，祝您使用愉快~~~

**Comment by shadowjohn** [comment]
申請結案~
