### ISSUE TITLE
在「半形」狀態下，切換中英輸入法，狀態列會整個消失，在「全形」反而正常

### ISSUE THREAD

**Issue by cokeyko** [shadowjohn/UCL_LIU#36]
羽山大大您好，小弟在切換中英輸入時，遇到一個問題，說明如下：

在「半形」狀態下，切換為英文，浮動的狀態列會整個消失不見，雖然可以輸入英文，但狀態列不應該消失。

不過，在「全形」狀態下，切換為英文，狀態列不會消失，反而是符合期待的「肥 全」→「英 全」。

煩請大大查察，感謝您~

---作業環境----
Windows 10 家用版 21H2
肥米輸入法 1.52

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/213915063-750357b8-2ed1-4f4d-9f99-d50548303935.png)
您好，可以自行調整「英/半」時的透明度，預設是 10% 且在「英半」時，我設定成不會自動置頂，

鍵盤按 Win+M 全部縮小時，就沉底了，比 desktop 還低~所以消失是正常的^^
不然看電影還是其他全螢幕工作時，會有浮動條很礙事...
英半 目前這樣設置我覺得是很合理的作法，除非有其他用途，不然不會調整這部分呦 :)
如果您很在意在英半時也想看著輸入條，那麼程式碼在 1338 行左右，可自行調整^^

**Comment by cokeyko** [comment]
羽山大大您好，感謝您在新春期間還回覆小弟的問題。原來它沉到後面去了，難怪我之前調整透明度為100%也沒有用。

理解您的想法，我誤以為是小蟲，打擾您了。

平安喜樂 ^___^
