### ISSUE TITLE
Ctrl+Alt+Delete後肥米會吃不到輸入

### ISSUE THREAD

**Issue by Benson9954029** [shadowjohn/UCL_LIU#42]
症狀跟#38有點像 
不過#38比較像pyHook的問題,這個肥米沒掛掉按shift是正常的運作的
實測版本(1.56,1.55,1.5)
環境win11(1.56,1.55,1.5) windows sandbox(1.5) 不知道為什麼sandbox 打不開1.56 1.55

**Comment by shadowjohn** [comment]
收到~
該不會1.55跟1.56我是用win11環境編的關係 🌊 ?
來試試 ctrl+alt+del~

**Comment by shadowjohn** [comment]
![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/a96fb464-8241-46be-8127-eac8f737a00d)
工作管理員的畫面，得用
![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/48e27568-e825-41cf-8ee8-8ce34af23bd3)
勾選以系統管理員身分啟動肥米，才能正常使用~

然後剛才試了 ctrl+alt+del 在登入視窗時肥米無法出現，但進入系統後則可以正常使用

**Comment by Benson9954029** [comment]
不曉得是只有我還是其他人也會遇到，我勾了以後還是一樣

**Comment by Benson9954029** [comment]
![ucl](https://github.com/shadowjohn/UCL_LIU/assets/28132352/97bcc871-a141-4abd-9e20-4d86a8879e4a)
這是在沙箱錄的 本機情況是一樣的  如果有需要我再看看怎麼錄
對按完Ctrl+Alt+Del 後直接取消 就會像這樣子

**Comment by shadowjohn** [comment]
瞭解，我也試出來了
看來也是一樣沾黏的問題~
「肥模式時」登出畫面的一瞬間，輸入法仍以為 ctrl 未放開
ctrl 多按一下即正常

**Comment by shadowjohn** [comment]
晚上來修看看

**Comment by shadowjohn** [comment]
Hi~ @Benson9954029 
https://github.com/shadowjohn/UCL_LIU/tree/V1.57
https://github.com/shadowjohn/UCL_LIU/commit/2ebf158c3a27f95ca1cee7990a89be88cf092f47

這狀況也有其他人回報 event.Ascii 變 0 的問題
https://stackoverflow.com/questions/41652232/pyhook-giving-wrong-ascii-values

研究了許久，發現 ctrl+alt+del 回來後，在沒按 ctrl 前，event.ascii 取到的值都會變 0
嘗試想用 KeyID 解決，但 KeyID 無法判斷大小寫
暫時先用很髒的自動幫使用者偷按一次 ctrl 解決

總之先體驗看看，用陣子沒問題就合併到主線

**Comment by Benson9954029** [comment]
左control ok 右control 不行 哈哈

**Comment by shadowjohn** [comment]
哈~好像是，我再研究一下

**Comment by shadowjohn** [comment]
https://github.com/shadowjohn/UCL_LIU/tree/V1.57
https://github.com/shadowjohn/UCL_LIU/commit/3c0e7decb17fe87e517bafc533aa405adc721d2a

右邊的ctrl 也偷偷按一下
右邊的 ctrl 也可以了

**Comment by shadowjohn** [comment]
我來研究一下沙箱怎麼用

**Comment by shadowjohn** [comment]
![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/cf51b4dc-0ceb-473f-8cf9-8d9ca8bef049)
編成 debug 模式後，似乎看到在沙箱裡有 bug

**Comment by shadowjohn** [comment]
![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/74069e44-9ad7-4edc-991d-cb811eae32b3)
184、windows 沙箱在 1.55 版以後無法使用，發現是沙箱缺少 wmic.exe 指令 (感謝 Benson9954029 回報問題)
https://github.com/shadowjohn/UCL_LIU/commit/803e3ea50d4f940de2a1e707eff803d80d116af8

想用 wmic 來判斷使用者當前是否用 win11 ~
增加判斷如果沒有這個指令，就直接用 platform.version() 不過 python2.7 這個指令有點舊了
win11 判斷不出來，只能用已知的去處理~
最終只是用來判斷是不是  win11 跟新版的 notepad.exe 來切換上字的方法 :(

**Comment by Benson9954029** [comment]
手邊沒有windoes pc 可以試 可能要等禮拜一
抱歉 不過昨天有看一下code的作法 
再加上實作右邊control應該是不會出什麼問題

**Comment by Benson9954029** [comment]
Ctrl+Alt+Del
沙箱問題都解決囉   感謝迅速處理!
