### ISSUE TITLE
Enable/Disable 半形全形切換

### ISSUE THREAD

**Issue by Benson9954029** [shadowjohn/UCL_LIU#48]
最近換了一個65配列的鍵盤(鍵盤小 大鍵靠很近)，用線性軸很容易誤觸，打著打著就切到全形
目前有兩個解法大鍵換重手軸，修改肥米 我決定兩個都做 哈哈
code我fork 也改了 如果覺得有必要用再merge 沒有就跳過吧

**Comment by shadowjohn** [comment]
感謝大大出手相助~~
![小海獅舔愛心](https://github.com/shadowjohn/UCL_LIU/assets/1788472/f03cca17-5618-4613-bec9-1ccdf32fd287)

**Comment by shadowjohn** [comment]
從您 commit 上來的Code 感受到您已把肥米的開發方式摸透了，看起來在選單加了全形半形的鎖定開關， i18n 也作了，等會回家測看看，沒問題就合併

**Comment by Benson9954029** [comment]
其實沒有摸透 哈哈  我就是造樣造句

**Comment by shadowjohn** [comment]
![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/4a57fe25-8251-4f1e-a26f-230f93a66e0d)
@Benson9954029  試都正常
我稍微調整了選單的字句~
感謝擴充~~有時也會想關全形半形的切換，有選單確實方便

**Comment by shadowjohn** [comment]
@Benson9954029 
謝謝您的貢獻~~把您也加入作者 
![貓](https://github.com/shadowjohn/UCL_LIU/assets/1788472/f07c92e0-016a-4f2e-aa46-ee3cf3ef0692)
