### ISSUE TITLE
關於caps穿透的問題

### ISSUE THREAD

**Issue by kesdoputr** [shadowjohn/UCL_LIU#5]
不好意思，我是在ptt上有提出過caps熱鍵問題的，新版caps穿透以後大致上使用已經沒問題
不過有碰到一點小狀況(抱歉可能只有我會有這種狀況)

●我個人的設定是用caps+逗號輸出bs，現在新版以後我按這個熱鍵他會直接幫我做bs的動作
但是如果我打字打一半(肥米的上面有我還在輸入的字根)，這個時候我按caps+逗號還是會在
輸入文字的部分輸出bs，能不能在肥米上頭還有字根的時候，這個bs是送給肥米的？
(就是我可以在我打錯的時候直接用熱鍵倒退我在肥米上已經輸入的字根，這個部分我在官蝦和偽蝦
上面用都正常，不過在肥米上我要直接按鍵盤的BS才能倒退，用熱鍵的BS就會直接在我的編輯器上做用)

●新版caps穿透上幾乎都沒有問題了，不過我如果按住caps然後按shift還是會切換肥米
能不能設定成只要按住caps的話連shift都一起穿透過去？
(因為我用68key小鍵盤所以也有mapping是按住caps+shift和其他按鍵做輸出其他東西，現在這樣我在
輸出的時候字是會出去不過肥米視窗會一直出現消失出現消失)

您寫的肥米真的很好用，現在這個issue就是用肥米打的，上面的狀況可能只有我會碰到
等您有空更新的時候再幫忙看看這些問題吧，謝謝。

**Comment by shadowjohn** [comment]
1. capslock + bs = 優先刪除肥米的字
2. caps + shift 直接穿透

下版調整

**Comment by kesdoputr** [comment]
已經測試ok，太神速了！！m(_ _)m
