### ISSUE TITLE
簡根顯示錯誤

### ISSUE THREAD

**Issue by Benson9954029** [shadowjohn/UCL_LIU#51]
时(h1)的簡根應該是只有h1 沒有hv
満(m1)的簡根應該是只有m1 沒有mv
目前還沒空試，初步想法，在簡根幫user 加vrsf的同時，
一併在字根檔判斷有沒有已經有沒有字就可以了
ex hv已經有惟 mv已經有行  就不幫user加進簡根清單 應該就可以了吧?

**Comment by shadowjohn** [comment]
哦哦~~沒錯，有這個簡根提示的bug，看得真仔細
时->h1，hv->惟
會以為 hv 也可以選到 h1，但 hv 有惟這個字了
研究研究~

**Comment by shadowjohn** [comment]
感謝回報~~
晚上大概改了一下，進入測試~~

https://github.com/shadowjohn/UCL_LIU/tree/V1.61
![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/25f8fde0-ac36-41fc-ba61-7fc4bf610459)

时
![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/004f15b2-9bc4-41bb-9d62-de77a6798085)
満
![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/a9dd8b99-4210-4059-8275-9d423c0589fc)
娚
![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/c0a1fa16-b3b4-42dc-b4a2-bc7cd0f36247)

**Comment by Benson9954029** [comment]
試起來沒有問題 感謝您
