### ISSUE TITLE
右邊雙引號 』無法快速輸出

### ISSUE THREAD

**Issue by hrcspkla** [shadowjohn/UCL_LIU#55]
過去使用嘸蝦米Ｊ輸入雙引號『』時，都習慣連按兩下 [ 鍵以及 ] 鍵。但在肥米時，按兩下 [ 可以看到組字視窗有出現左邊雙引號 『 但右邊雙引號與其它右側符號就沒有。必須改用　_, ] ]_　（多一個逗號）這樣的輸入方式，才會出現右邊雙引號。

**Comment by shadowjohn** [comment]
@hrcspkla 您好,

這個是字根表的問題，您可以用 notepad++ 編輯 liu.json 
以我的字根表大概在 3475 行左右
擴充一下就可以照原來的習慣出字嘍^^
"]]": [
      "』"
],

改完後肥米要關掉再重開

![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/3a11964f-23e9-40c6-814a-3d6170bc4546)
![image](https://github.com/shadowjohn/UCL_LIU/assets/1788472/41686f6f-fe80-4481-a20b-6428253f8265)

**Comment by shadowjohn** [comment]
是個喜歡各種符號的朋友呢~

**Comment by shadowjohn** [comment]
@hrcspkla 
喜歡各種符號的朋友，我要結案嘍~
