### ISSUE TITLE
肥半時中文輸出模式時，標點符號可以是選擇是半型嗎？

### ISSUE THREAD

**Issue by devenhala** [shadowjohn/UCL_LIU#57]
肥半時中文輸出模式時，標點符號可以是選擇是半型嗎？
謝謝。

**Comment by shadowjohn** [comment]
不能的，請切回英半再打吧~ ,,,,,,,,,,,,,,

**Comment by devenhala** [comment]
了解，謝謝。

**Comment by shadowjohn** [comment]
> 了解，謝謝。

如果非常想打半形逗號的話,可以編輯 liu.json 
找到出逗號的地方,加一個半型的在前面,存檔後再重開肥米即可享用
改之前最好先備份一下,免得改壞了,用 notepad++ 改比較不會壞掉

![image](https://github.com/user-attachments/assets/a45cf1ad-5033-4a65-9046-4a64610298cb)

![image](https://github.com/user-attachments/assets/3161b3b7-606d-4dee-8990-33563bd88d46)

**Comment by devenhala** [comment]
這方法看來可行哦,謝謝。

**Comment by shadowjohn** [comment]
> 這方法看來可行哦,謝謝。
好的, 會贏呦
