### ISSUE TITLE
關於肥米與AHK輸出字串速度的問題

### ISSUE THREAD

**Issue by kesdoputr** [shadowjohn/UCL_LIU#6]
您好，不好意思又有點問題想請教，用最新版之後大致上在打字上頭已經沒有任何問題
現在是有一個小問題關於開了肥米之後AHK輸出的方面：

我有在用AHK做熱鍵的mapping還有輸出一些常用的字串和複製貼上之類的
我發覺在肥米有執行的時候(不論是什麼模式，只要查目前執行程式有uclliu)
本來我輸出的字串是一瞬間完成，在肥米有執行的時候就會變成慢慢的送出

怕光用文字說明不好理解，可否請您測試看看把以下的例子存成.ahk然後用ahk跑它之後
在肥米有執行與沒執行的狀況下輸入/qqq，應該可以發現這兩者輸出的速度有差異
不知道是不是肥米執行以後會去攔截和偵測使用者輸入的關係？謝謝。

-----
#Hotstring T ? *
::/qqq:: 臣亮言：先帝創業未半，而中道崩殂，今天下三分，益州疲敝，此誠危急存亡之秋也。然侍衞之臣不懈於內，忠志之士忘身於外者，蓋追先帝之殊遇
-----

**Comment by shadowjohn** [comment]
@kesdoputr  [http://3wa.tw/uploads/upload/2019-03-08.mp4](url)

我覺得好像差不多呢

**Comment by kesdoputr** [comment]
唔，我回到家裡測試發現速度也是差不多，可能公司有些什麼
後台程式導致我在公司用的時候兩者的速度完全不一樣，不好意思打擾了，我把這個issue關掉。XD
