### ISSUE TITLE
字根檔

### ISSUE THREAD

**Issue by weijen6** [shadowjohn/UCL_LIU#7]
您好
請問能否支援小小輸入法臺灣包2018年版wuxiami.txt?
http://fygul.blogspot.com/2018/05/yong-tw2018.html
linux包中的/tw/wuxiami.txt

另外，opendesktop提供的萬國蝦米字根檔uniliu.txt
應該可以內建使用?
https://github.com/chinese-opendesktop/cin-tables

**Comment by shadowjohn** [comment]
好啊~我來試看看~
下面那個連結的管理者 bluebat 是我以前的主管 :~

**Comment by shadowjohn** [comment]
剛才測了一下，更新了程式，只要更新至 1.17 版，這二個版本都可以支援~
1﹑wuxiami.txt ，與 uclliu.exe 放一起就可以用了

2、(原本就支援了) 支援opendesktop提供的萬國蝦米字根檔uniliu.txt，https://github.com/chinese-opendesktop/cin-tables，同fcitx 嘸蝦米表格，將uniliu.txt 改名成 fcitx_boshiamy.txt 跟主程式放一起(可惜沒有日文字)

**Comment by shadowjohn** [comment]
不知道您試了沒，這題我要結案了

**Comment by weijen6** [comment]
> 不知道您試了沒，這題我要結案了

您好，感謝，測試正常

**Comment by shadowjohn** [comment]
感謝支持~祝使用愉快
